pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
      label:
        add: [dependency-update]
