CREATE TABLE JWT (
  ID VARCHAR PRIMARY KEY,
  JWT VARCHAR NOT NULL,
  -- BIGINT instead of BIGSERIAL
  IDENTITY BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
  EXPIRY TIMESTAMP NOT NULL,
  LAST_TOUCHED TIMESTAMP
);

ALTER TABLE ORDERS
  ADD USER_ID BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE USERS
  ADD ROLE VARCHAR NOT NULL DEFAULT 'Customer'
