CREATE TABLE JWT(
  ID VARCHAR PRIMARY KEY,
  JWT VARCHAR NOT NULL,
  -- BIGINT instead of BIGSERIAL
  IDENTITY BIGINT NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
  EXPIRY TIMESTAMP NOT NULL,
  LAST_TOUCHED TIMESTAMP,
);
